-   id: clean-sandboxer
    name: Clean Sandboxer
    description: Remove unchanged sandboxer template files.
    entry: sandboxer --clean
    language: system
    always_run: True
    pass_filenames: False
